<!DOCTYPE HTML>
<html lang="en">
<head>
    <title>Slicr::<?php echo $this->getRequest()->controller ?>::<?php echo $this->getRequest()->action; ?></title>
	<link type="text/css" rel="stylesheet" media="all" href="/css/style.css" />
    <script src="/js/prototype.js"></script>
</head>
<body>
    <div id="main">
		<div class="reps">
			<?php if( Nano_Session::session()->auth == true ): ?>
			<div id="top-bar" class="wrap">
				<div class="padding">
					<h1 class="float-left">PICO - site title</h1>
					<a href="/">view site</a> |
					<a href="/user/logout">logout</a>
				</div>
			</div>
			<div id="main-menu">
				<div class="padding">
					<?php echo $this->modules() ?>
				</div>
			</div>
			<div id="menu-left">
				<div class="padding">
					<?php echo $this->linkList( $this->actions ) ?>
				</div>
			</div>
			<?php endif; ?>
			<div id="main-content">
				<div class="padding">
					<?php echo $this->getView() ?>
					<!-- Insert your content here -->
				</div>
			</div>
		</div>
    </div>
</body>
</html>
