<!DOCTYPE HTML>
<html lang="en">
<head>
    <title>Slicr::<?php echo $this->getRequest()->controller ?>::<?php echo $this->getRequest()->action; ?></title>
	<link type="text/css" rel="stylesheet" media="all" href="/css/layout.css" />
    <script src="/js/prototype.js"></script>
</head>
<body>
    <div id="main">
        <?php if( Nano_Session::session()->auth == true ): ?>
        <div id="main-menu">
            <?php echo $this->modules() ?>
        </div>
        <div>
            <?php echo $this->linkList( $this->actions ) ?>
        </div>
        <?php endif; ?>
        <div class="reps">
        <?php echo $this->getView() ?>
        <!-- Insert your content here -->
        </div>
    </div>
</body>
</html>
