<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title><?php echo $this->config->blogTitle ?></title>
	<link type="text/css" rel="stylesheet" media="all" href="css/layout.css" />
</head>
<body>
    <div id="head">
        <h1><a href="/"><?php echo $this->config->blogTitle ?></a></h1>
        <div id="user">
            <?php if( $this->session->user ): ?>
                <span>Hi, <?php echo $this->config->user ?></span>
                <a href="/add">create a new post</a> | <a href="/logout">logout</a>
            <?php else: ?>
            <form action="/login" method="post">
                <label for="username">
                    username
                    <input type="text" id="username" name="username"/>
                </label>
                <label for="password">
                    password
                    <input type="password" id="password" name="password" />
                </label>
                <input type="submit" value="login" />
            </form>
            <?php endif; ?>
        </div>
    </div>
    <div id="sidebar">
        <h4>Categories</h4>
        <ul>
        <?php if( $this->categories ): foreach( $this->categories as $cat ): ?>
            <li><a href="/category/<?php echo $cat ?>"><?php echo $cat ?></a></li>
        <?php endforeach; endif;?>
        </ul>
    </div>
    <div id="content">
        <?php echo $this->content ?>
    </div>
</body>
</html>
