<?php $this->inherit( 'layout') ?>

<?php $this->block('context-navigation') ?>
<?php $this->endblock('context-navigation') ?>

<?php $this->block('secondary-navigation') ?>
<ul class="wat-cf">
    <li class="<?php echo $this->request->action == 'list' ? 'active' :'' ?>"><a href="/admin/image/list">show all images</a></li>
    <li class="<?php echo $this->request->action == 'label' ? 'active' :'' ?>"><a href="/admin/image/label">show labels</a></li>
</ul>
<?php $this->endblock('secondary-navigation') ?>
