<!DOCTYPE html>
<html lang="en">
<head>
    <title></title>
    <script src="/js/jquery-1.4.2.min.js"></script>
    <script src="/js/jquery-ui-1.8.4.custom.min.js"></script>
    <?php $this->block( 'head' ); ?>
    <link type="text/css" rel="stylesheet" media="all" href="/css/admin/base.css" />
    <link type="text/css" rel="stylesheet" media="all" href="/css/admin/style.css" />
    <link type="text/css" rel="stylesheet" media="all" href="/css/admin/layout.css" />
    <?php $this->endBlock( 'head' ); ?>
</head>
<body>
    <div id="container">
        <div id="header">
            <h1><a href="index.html">Web App Theme</a></h1>
            <div id="user-navigation">
              <ul class="wat-cf">
                <li><a href="#">Profile</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#" class="logout">Logout</a></li>
              </ul>
            </div>
            <div id="main-navigation">
              <ul class="wat-cf">
                <li class="first"><a href="#block-text">Main Page</a></li>
                <li class="active"><a href="#block-text">Active</a></li>
                <li><a href="#block-login">Login</a></li>
                <li><a href="#block-signup">Signup</a></li>
              </ul>
            </div>
        </div>
        <div id="wrapper" class="wat-cf">
            <div id="main">
                <div class="block">
                    <div class="content">
                    <?php $this->block('main') ?>

                    <?php $this->endblock('main') ?>
                    </div>
                </div>
            </div>
            <div id="sidebar">
                <?php $this->block('sidebar') ?>

                <?php $this->endblock('sidebar') ?>
            </div>
        </div>

    </div>
</body>
</html>
