<!DOCTYPE html>
<html lang="en">
<head>
    <title></title>
    <script src="/js/jquery-1.9.1.js"></script>
    <script src="/js/jquery-ui-1.10.1.custom.js"></script>
    <script src="/js/sentry.plugin.js"></script>
    <script src="/js/nano.js"></script>
    <link type="text/css" rel="stylesheet" media="all" href="/css/admin/layout.css" />
    <?php $this->block( 'head' ); ?>
    <?php $this->endBlock( 'head' ); ?>
</head>
<body>
    <div id="container">
        <div id="header">
            <div id="user-navigation">
              <ul class="wat-cf">
                <?php
                    $link_title = 'View website';
                    $link_path  = '/';
                    
                    if( isset( $item ) ){
                        $link_title = 'View page';
                        $link_path  = '/' . $item->slug;                        
                    }
                ?>
                <li><a target="blank" href="<?php echo $link_path ?>"><?php echo $link_title ?></a></li>
                <li><a href="/admin/user/logout" class="logout">Logout</a></li>
              </ul>
            </div>
            <h1><a href="/">pico</a></h1>
            <div id="main-navigation">
              <ul class="wat-cf">
                <li><a href="/admin/image">images</a></li>
                <li><a href="/admin/page">pages</a></li>
                <?php $this->block('module-navigation') ?>
                <!-- define module defined navigation here -->
                <?php $this->endblock('module-navigation') ?>
              </ul>
            </div>
        </div>
        <div id="context-navigation">
        <?php $this->block('context-navigation') ?>
        <!-- define module defined navigation here -->
        <?php $this->endblock('context-navigation') ?>
        </div>
        <div id="wrapper" class="wat-cf">
            <div id="main">
                <div class="block">
                    <div class="secondary-navigation">
                    <?php $this->block('secondary-navigation') ?>
                    <!-- define module defined navigation here -->
                    <?php $this->endblock('secondary-navigation') ?>
                    </div>
                    <div id="titlebar">
                    <?php $this->block('titlebar') ?>
                    <!-- define module defined navigation here -->
                    <?php $this->endblock('titlebar') ?>
                    </div>
                    <div class="content">
                    <?php $this->block('main') ?>
                    <!-- define module defined content here -->
                    <?php $this->endblock('main') ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        $('form.autosave').sentry({ events: 'change keyup' });
        
        $(document).ajaxStart( function(){
            $("input[type='submit']").attr('disabled', true );
            $('body, iframe').css( { cursor: 'wait' } );
        });

        $(document).ajaxStop( function(){
            $("input[type='submit']").attr('disabled', false );
            $('body, iframe').css( { cursor: 'default' } );
        });
    </script>
</body>
</html>
