<!DOCTYPE html>
<html lang="en">
<head>
    <title></title>
    <script src="/js/jquery-1.6.4.min.js"></script>
    <script src="/js/jquery-ui-1.8.16.custom.min.js"></script>
    <script src="/js/nano.js"></script>
    <link type="text/css" rel="stylesheet" media="all" href="/css/admin/jquery-ui.css" />
    <link type="text/css" rel="stylesheet" media="all" href="/css/admin/layout.css" />
    <?php $this->block( 'head' ); ?>
    <?php $this->endBlock( 'head' ); ?>
</head>
<body>
    <div id="container">
        <div id="header">
            <div id="user-navigation">
              <ul class="wat-cf">
                <!-- <li><a href="#">Profile</a></li> !-->
                <!-- <li><a href="#">Settings</a></li> !-->
                <li><a href="/">View website</a></li>
                <li><a href="#" class="logout">Logout</a></li>
              </ul>
            </div>
            <h1><a href="/">pico</a></h1>
            <div id="main-navigation">
              <ul class="wat-cf">
                <li><a href="/admin/image">images</a></li>
                <li><a href="/admin/page">pages</a></li>
                <li><a href="/admin/image">settings</a></li>
              </ul>
            </div>
        </div>
        <div id="context-navigation">
        <?php $this->block('context-navigation') ?>
        <!-- define module defined navigation here -->
        <?php $this->endblock('context-navigation') ?>
        </div>
        <div id="wrapper" class="wat-cf">
            <div id="main">
                <div class="block">
                    <div class="secondary-navigation">
                    <?php $this->block('secondary-navigation') ?>
                    <!-- define module defined navigation here -->
                    <?php $this->endblock('secondary-navigation') ?>
                    </div>
                    <div id="titlebar">
                    <?php $this->block('titlebar') ?>
                    <!-- define module defined navigation here -->
                    <?php $this->endblock('titlebar') ?>
                    </div>
                    <div class="content">
                    <?php $this->block('main') ?>
                    <!-- define module defined content here -->
                    <?php $this->endblock('main') ?>
                    </div>
                </div>
            </div>
        </div>

    </div>
</body>
</html>
