<?php $this->inherit( dirname(__FILE__) . '/../layout') ?>

<?php $this->block('head') ?>
<?php $this->endblock('head') ?>

<?php $this->block('titlebar') ?>
<div class="align-right wrap">
    <h2 class="float-left">Delete <span style="color:#000;"><?php echo $item->name ?></span></h2>
</div>
<?php $this->endblock('titlebar') ?>


<?php $this->block('main') ?>
<div class="half" style="width: 480px;">
    <form class="form" method="POST" action="/admin/common/delete/<?php echo $item->id ?>">
        <p>Are you sure you wish to delete <a href=""><?php echo $item->type . " " . $item->name ?></a>?</p>
        <br/>
        <div class="toolbar">
            <input type="submit" class="input-submit" name="cancel" value="No! Cancel!" />
            <input type="submit" class="input-submit" name="confirm" value="Delete" />
        </div>
    </form>
</div>
<div class="right-pane">
</div>
<?php $this->endblock('main') ?>
