ALTER TABLE `image_data` MODIFY `created` TIMESTAMP NOT NUL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `item` MODIFY `appendix` LONGBLOB NOT NULL DEFAULT '';
ALTER TABLE `item` MODIFY `description` VARCHAR(2048) NOT NULL DEFAULT '';
ALTER TABLE `item` MODIFY `name` VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE `item` MODIFY `visible` TINYINT(2) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `item` MODIFY `parent` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `item` MODIFY `priority` INT UNSIGNED NOT NULL DEFAULT 0;
