<?php $this->wrapper('layout') ?>

<?php $this->block('head') ?>
<?php $this->endblock('head') ?>

<?php $this->block('titlebar') ?>
<div class="align-right wrap">
    <h2 class="float-left">Editing <span style="color:#000;"><?php echo $item->name ?></span></h2>
    <a href="/admin/page/content/<?php echo $item->id ?>" class="button">add content</a>
    <a class="button" href="/admin/page/delete/<?php echo $item->id ?>">delete</a>
</div>
<?php $this->endblock('titlebar') ?>

<?php $this->block('main') ?>
<div id="vertical-nav" class="fifth">
    <ul class="verticalnav">
        <li><h4>Pages</h4></li>
        <?php foreach( $this->items('page') as $page ): ?>
        <li><a class="<?php echo $page->id == $item->id ? "active":"" ?>" href="/admin/page/edit/<?php echo $page->id ?>"><?php echo $page->name ?></a></li>
        <?php endforeach; ?>
    </ul>
    <?php $this->block('sidebar') ?>
    <?php $this->endblock('sidebar') ?>
</div>
<div class="three-fifth">
    <?php echo $this->form ?>
    <?php $this->process( 'common/content' ); ?>
</div>
<?php $this->endblock('main') ?>