<?php $this->wrapper('layout') ?>

<?php $this->block('head') ?>
<script type="text/javascript" src="/js/light-rte/jquery.rte.js"></script>
<script type="text/javascript">
jQuery(document).ready(function(){
    $('.rich-text-editor').rte({
        content_css_url: "/js/light-rte/rte.css",
        media_url: "",
    });

});
</script>
<?php $this->endblock('head') ?>

<?php $this->block('titlebar') ?>
<div class="align-right wrap">
    <h2 class="float-left">Editing <span style="color:#000;"><?php echo $item->name ?></span></h2>
    <a href="/admin/page/content/<?php echo $item->id ?>" class="button">add content</a>
    <a class="button" href="/admin/page/delete/<?php echo $item->id ?>">delete</a>
</div>
<?php $this->endblock('titlebar') ?>

<?php $this->block('main') ?>
<div id="vertical-nav" class="fifth">
    <ul class="verticalnav">
        <li><h4>pages</h4></li>
        <?php foreach( $this->items('page') as $page ): ?>
        <li><a class="<?php echo $item->id == $page->id ? "active":"" ?>" href="/admin/page/edit/<?php echo $page->id ?>"><?php echo $page->name ?></a></li>
        <?php endforeach; ?>
    </ul>
    <?php $this->block('sidebar') ?>
    <?php $this->endblock('sidebar') ?>
</div>
<div class="three-fifth">
    <?php echo $this->form ?>
    <?php foreach( $item->content() as $content ): ?>
        <?php echo new Pico_Form_Content( $content ); ?>
    <?php endforeach; ?>
</div>
<?php $this->endblock('main') ?>
