<?php $this->wrapper( 'image') ?>

<?php $this->block('head') ?>
<?php $this->endblock('head') ?>

<?php $this->block('titlebar') ?>
<div class="align-right wrap">
    <h2 class="float-left">Editing <span style="color:#000;"><?php echo $image->name ?></span></h2>
    <a href="/admin/image/content/<?php echo $image->id ?>" class="button">add content</a>
    <a href="/admin/image/delete/<?php echo $image->id ?>" class="button">delete</a>
</div>
<?php $this->endblock('titlebar') ?>


<?php $this->block('main') ?>
<div class="left-pane">
    <?php echo $form; ?>
    <?php $this->process( 'common/content', array( 'item' => $image ) ); ?>
</div>
<div class="right-pane">
    <div id="imagecrop">
        <img onload="this.parentNode.scrollTop=(this.height/8);this.parentNode.scrollLeft=(this.width/5);" align="center" src="/image/sd/<?php echo $image->id ?>" />
    </div>
</div>
<?php $this->endblock('main') ?>
