<?php $this->inherit( 'image') ?>

<?php $this->block('head') ?>
<script type="text/javascript" src="/js/light-rte/jquery.rte.js"></script>
<script type="text/javascript">
jQuery(document).ready(function(){
    $('.rich-text-editor').rte({
        content_css_url: "/js/light-rte/rte.css",
        media_url: "",
    });

});

</script>
<?php $this->endblock('head') ?>

<?php $this->block('titlebar') ?>
<div class="align-right wrap">
    <h2 class="float-left">Editing <span style="color:#000;"><?php echo $image->name ?></span></h2>
    <a href="/admin/content/add/<?php echo $image->id ?>" class="button">add content</a>
    <a href="/admin/common/delete/<?php echo $image->id ?>" class="button">delete</a>
</div>
<?php $this->endblock('titlebar') ?>


<?php $this->block('main') ?>
<div class="left-pane">
    <?php echo $form; ?>
    <?php foreach( $image->content as $content ): ?>
        <?php echo new Form_Content( $content ); ?>
    <?php endforeach; ?>
</div>
<div class="right-pane">
    <div id="imagecrop">
        <img onload="this.parentNode.scrollTop=(this.height/8);this.parentNode.scrollLeft=(this.width/5);" align="center" src="/image/sd/<?php echo $image->id ?>" />
    </div>
</div>
<?php $this->endblock('main') ?>
