<?php $this->inherit( 'image') ?>

<?php $this->block('head') ?>
<script type="text/javascript" src="/js/light-rte/jquery.rte.js"></script>
<script type="text/javascript">
jQuery(document).ready(function(){
    $('.rich-text-editor').rte({
        content_css_url: "/js/light-rte/rte.css",
        media_url: "",
    });

});
</script>
<?php $this->endblock('head') ?>

<?php $this->block('titlebar') ?>
<div class="align-right wrap">
    <h2 class="float-left">Editing <span style="color:#000;"><?php echo $label->name ?></span></h2>
    <a href="/admin/content/add/<?php echo $label->id ?>" class="button">add content</a>
    <a class="button" href="/admin/common/delete/<?php echo $label->id ?>">delete</a>
</div>
<?php $this->endblock('titlebar') ?>


<?php $this->block('main') ?>
<div class="left-pane">
    <?php echo $this->form ?>
    <?php foreach( $label->content as $content ): ?>
        <?php echo new Form_Content( $content ); ?>
    <?php endforeach; ?>
</div>
<div class="right-pane">
</div>
<?php $this->endblock('main') ?>
