<?php $this->inherit( 'image') ?>

<?php if( null !== $this->request->id ): ?>
<?php $this->block( 'head' ); ?>
<script>
$(function(){
    $(".input-priority").hide();
    $("ul.thumbnails").sortable({ update: function(evt, ui){
        $(".input-priority").each(function(i,el){
            el.value = i
        });
        //$('#images').attr('action', '/admin/image/order/<?php echo $request->id ?>');
        //$('#images').submit();
        $.ajax({
            url: '/admin/image/order/<?php echo $request->id ?>',
            type: 'POST',
            data: $('#images').serialize(),
            success: function( data, status, xhr ){
                console.log(data);
            }
        })
}})});
</script>
<?php $this->endBlock('head'); ?>
<?php endif; ?>


<?php $this->block('sidebar') ?>
<?php $this->endblock('sidebar') ?>

<?php $this->block('titlebar') ?>
<h2 class="title">images</h2>
<a href="/admin/image/upload" onclick="return nano.ahah.link(this, 'form')" class="context-button">upload image</a>

<?php $this->endblock('titlebar') ?>


<?php $this->block('main') ?>
<div id="vertical-nav" class="fifth">
    <ul class="verticalnav">
        <li><h4>labels</h4></li>
        <li><a class="<?php echo null == $request->id ? "active" : "" ?>" href="/admin/image/list">all available images</a></li>
        <?php foreach( $labels as $label ): ?>
        <li><a class="<?php echo $label->id == $request->id ? "active":"" ?>" href="/admin/image/list/<?php echo $label->id ?>"><?php echo $label->name ?></a></li>
        <?php endforeach; ?>
    </ul>
</div>
<div class="three-fifth">
    <form id="images" class="form" method="post" action="<?php echo $request->url() ?>">
        <div class="toolbar" style="text-align:right;">
            <div class="third">
                select:
                <a href="#select-all" onclick="$('ul.thumbnails').find('input').attr('checked', true)">all</a>,
                <a href="#select-none" onclick="$('ul.thumbnails').find('input').attr('checked', false)">none</a>
            </div>
            <button onclick="nano.ahah.form(this.form, 'form', this); return false;" id="action-labels" class="button" value="labels" name="form_action_labels">edit labels</button>
            <button onclick="return false;" id="action-delete" class="button" value="labels" name="form_action_delete">delete</button>
        </div>
        <ul class="thumbnails">
            <?php foreach( $images as $image ): ?>
            <li>
                <dl>
                    <dt>
                        <input class="checkbox" type="checkbox" id="image-edit-<?php echo $image->id ?>" name="image[<?php echo $image->id ?>]" value="<?php echo $image->id ?>" />
                        <label for="image-edit-<?php echo $image->id ?>">
                            <span><?php echo $image->name ?></span>
                        </label>
                        <input class="input-priority" name="priority[<?php echo $image->id ?>]" value="<?php echo intval($image->priority) ?>" />
                    </dt>
                    <dd>
                        <label for="image-edit-<?php echo $image->id ?>">
                        <a onclick="return false;" ondblclick="document.location.href=this.href" href="/admin/image/edit/<?php echo $image->id ?>" title="edit <?php $image->title ?>">
                            <img src="/image/thumbnail/<?php echo $image->id ?>" alt=""/>
                        </a>
                        </label>
                    </dd>
                </dl>
            </li>
            <?php endforeach; ?>
        </ul>
        <div class="pager">
            <ul class="pager">
                <li><a href="?page=<?php echo $pager->firstPage ?>">&laquo; first</a>
                <li>
                <?php if($pager->previousPage): ?>
                    <a href="?page=<?php echo $pager->previousPage ?>">&laquo; previous</a>
                <?php else: ?>
                    <span class="disabled">&laquo; previous</span>
                <?php endif; ?>
                </li>
                <?php foreach( $pager->range(20) as $i ): ?>
                <li><a class="<?php echo $pager->currentPage == $i ? 'active' : '' ?>" href="?page=<?php echo $i ?>"><?php echo $i ?></a></li>
                <?php endforeach; ?>
                <li>
                <?php if($pager->nextPage): ?>
                    <a href="?page=<?php echo $pager->nextPage ?>">next &raquo;</a>
                <?php else: ?>
                    <span class="disabled">next &raquo;</span>
                <?php endif; ?>
                </li>
                <li><a href="?page=<?php echo $pager->lastPage ?>">last &raquo;</a></li>
            </ul>
        </div>
    </form>
<?php $this->endblock('main') ?>
