<?php $this->inherit('admin/template/image/image') ?>

<?php if( null !== $this->request->id ): ?>
<?php $this->block( 'head' ); ?>
<script>
$(function(){
    $(".item-priority").hide();
    $("#image-list").sortable({ update: function(evt, ui){
        $(".item-priority").each(function(i,el){
            el.value = i
        });
    }});
});
</script>
<?php $this->endBlock('head'); ?>
<?php endif; ?>


<?php $this->block('sidebar') ?>
<?php $this->endblock('sidebar') ?>

<?php $this->block('titlebar') ?>
<h2 class="title">images</h2>
<a href="/admin/image/upload" class="context-button">upload image</a>

<?php $this->endblock('titlebar') ?>


<?php $this->block('main') ?>
<div class="fifth">
    <ul class="verticalnav">
        <li><h4>labels</h4></li>
        <li><a class="<?php echo null == $request->id ? "active" : "" ?>" href="/admin/image/list">all available images</a></li>
        <?php foreach( $labels as $label ): ?>
        <li><a class="<?php echo $label->id == $request->id ? "active":"" ?>" href="/admin/image/list/<?php echo $label->id ?>"><?php echo $label->name ?></a></li>
        <?php endforeach; ?>
    </ul>
</div>
<div class="three-fifth">
    <form class="form" method="post">
        <div class="toolbar" style="text-align:right;">
            <div class="third">
                select:
                <a href="#select-all">all</a>,
                <a href="#select-none">none</a>
            </div>
            <button class="button" value="labels" name="form-action">edit labels</button><button class="button" value="labels" name="form-action">delete</button>
        </div>
        <ul class="thumbnails">
            <?php foreach( $images as $image ): ?>
            <li>
                <dl>
                    <dt>
                        <input class="checkbox" type="checkbox" id="image-edit-<?php echo $image->id ?>" name="image[<?php echo $image->id ?>]" value="<?php echo $image->id ?>" />
                        <label for="image-edit-<?php echo $image->id ?>">
                            <span><?php echo $image->name ?></span>
                        </label>
                    </dt>
                    <dd>
                        <label for="image-edit-<?php echo $image->id ?>">
                        <a onclick="return false;" ondblclick="document.location.href=this.href" href="/admin/image/edit/<?php echo $image->id ?>" title="edit <?php $image->title ?>">
                            <img src="/image/thumbnail/<?php echo $image->id ?>" alt=""/>
                        </a>
                        </label>
                    </dd>
                </dl>
            </li>
            <?php endforeach; ?>
        </ul>
    </form>
<!--    <div class="actions-bar wat-cf">
        <div class="actions">
          <button type="submit" class="button">
            <img alt="Delete" src="/css/admin/images/icons/cross.png"> Delete
          </button>
        </div>
        <div class="pagination">
          <span class="disabled prev_page">&laquo; revious</span>
          <span class="current">1</span><a href="#" rel="next">2</a><a href="#">3</a><a href="#">4</a><a href="#">5</a><a href="#">6</a><a href="#">7</a><a href="#">8</a><a href="#">9</a><a href="#">10</a><a href="#">11</a>
          <a href="#" class="next_page" rel="next">Next &raquo;</a>
        </div>
    </div>
--></div>
<?php $this->endblock('main') ?>
