<?php $this->wrapper( 'image') ?>

<?php if( null !== $id ): ?>
<?php $this->block( 'head' ); ?>
<script>
$(function(){
    $(".input-priority").hide();
    $("ul.thumbnails").sortable({ update: function(evt, ui){
        $(".input-priority").each(function(i,el){
            el.value = i
        });
        //$('#images').attr('action', '/admin/image/order/<?php echo $id ?>');
        //$('#images').submit();
        $.ajax({
            url: '/admin/image/order/<?php echo $id ?>',
            type: 'POST',
            data: $('#images').serialize(),
        })
}})});
</script>
<?php $this->endBlock('head'); ?>
<?php endif; ?>


<?php $this->block('sidebar') ?>
<?php $this->endblock('sidebar') ?>

<?php $this->block('titlebar') ?>
<h2 class="title">images</h2>
<a href="/admin/image/upload" id="context-activate-upload" class="context-button">upload image</a>

<?php $this->endblock('titlebar') ?>


<?php $this->block('main') ?>
<div id="vertical-nav" class="fifth">
    <ul class="verticalnav">
        <li><h4>labels</h4></li>
        <li><a class="<?php echo null == $id ? "active" : "" ?>" href="/admin/image/list">all available images</a></li>
        <?php foreach( $labels as $label ): ?>
        <li><a class="<?php echo $label->id == $id ? "active":"" ?>" href="/admin/image/list/<?php echo $label->id ?>"><?php echo $label->name ?></a></li>
        <?php endforeach; ?>
    </ul>
</div>
<div id="main-left" class="three-fifth">
    <div id="upload-form-container" style="display:none;">
        <?php $this->process( 'image/block/upload' ); ?>        
    </div>

    <form id="images" class="form" method="post" action="/admin/image/bulk/<?php echo $id ?>">
        <div class="toolbar" style="text-align:right;">
            <div class="fifth">
                select:
                <a href="#select-all" onclick="$('ul.thumbnails').find('input').attr('checked', true)">all</a>,
                <a href="#select-none" onclick="$('ul.thumbnails').find('input').attr('checked', false)">none</a>
            </div>
            <button id="action-delete" class="button" value="delete" name="action-delete">delete images</button>
            <button id="action-labels" class="button" value="labels" name="action-labels">edit labels</button>
        </div>
        <?php if( $pager->total > 1 ): ?>
        <div class="pager">
            <ul class="pager">
                <li><a href="?page=<?php echo $pager->firstPage ?>">&laquo; first</a>
                <li>
                <?php if($pager->previousPage): ?>
                    <a href="?page=<?php echo $pager->previousPage ?>">&laquo; previous</a>
                <?php else: ?>
                    <span class="disabled">&laquo; previous</span>
                <?php endif; ?>
                </li>
                <?php foreach( $pager->range(20) as $i ): ?>
                <li><a class="<?php echo $pager->currentPage == $i ? 'active' : '' ?>" href="?page=<?php echo $i ?>"><?php echo $i ?></a></li>
                <?php endforeach; ?>
                <li>
                <?php if($pager->nextPage): ?>
                    <a href="?page=<?php echo $pager->nextPage ?>">next &raquo;</a>
                <?php else: ?>
                    <span class="disabled">next &raquo;</span>
                <?php endif; ?>
                </li>
                <li><a href="?page=<?php echo $pager->lastPage ?>">last &raquo;</a></li>
            </ul>
        </div>
        <?php endif; ?>
        <ul class="thumbnails">
            <?php foreach( $images as $image ): ?>
            <li>
                <dl>
                    <dt>
                        <input class="checkbox" type="checkbox" id="image-edit-<?php echo $image->id ?>" name="image[<?php echo $image->id ?>]" value="<?php echo $image->id ?>" />
                        <label for="image-edit-<?php echo $image->id ?>">
                            <span><?php echo $image->name ?></span>
                        </label>
                        <input class="input-priority" name="priority[<?php echo $image->id ?>]" value="<?php echo intval($image->priority) ?>" />
                    </dt>
                    <dd>
                        <label for="image-edit-<?php echo $image->id ?>">
                        <a onclick="return false;" ondblclick="document.location.href=this.href" href="/admin/image/edit/<?php echo $image->id ?>" title="edit <?php $image->title ?>">
                            <img src="/image/thumbnail/<?php echo $image->id ?>" alt=""/>
                        </a>
                        </label>
                    </dd>
                </dl>
            </li>
            <?php endforeach; ?>
        </ul>
        <?php if( $pager->total > 1 ): ?>
        <div class="pager">
            <ul class="pager">
                <li><a href="?page=<?php echo $pager->firstPage ?>">&laquo; first</a>
                <li>
                <?php if($pager->previousPage): ?>
                    <a href="?page=<?php echo $pager->previousPage ?>">&laquo; previous</a>
                <?php else: ?>
                    <span class="disabled">&laquo; previous</span>
                <?php endif; ?>
                </li>
                <?php foreach( $pager->range(20) as $i ): ?>
                <li><a class="<?php echo $pager->currentPage == $i ? 'active' : '' ?>" href="?page=<?php echo $i ?>"><?php echo $i ?></a></li>
                <?php endforeach; ?>
                <li>
                <?php if($pager->nextPage): ?>
                    <a href="?page=<?php echo $pager->nextPage ?>">next &raquo;</a>
                <?php else: ?>
                    <span class="disabled">next &raquo;</span>
                <?php endif; ?>
                </li>
                <li><a href="?page=<?php echo $pager->lastPage ?>">last &raquo;</a></li>
            </ul>
        </div>
        <?php endif; ?>
    </form>

<script>
    $( '#context-activate-upload' ).click(function(evt){
        $('.ahah-generated').slideUp(function(){ $(this).remove() });
        $( '#upload-form-container' ).slideDown();
        evt.preventDefault();
    });
    
    $('#images').nanoAhahForm(function( html ){
        $(html).hide();
        $( '#upload-form-container' ).slideUp();
        $(html).slideDown('medium');
    });

</script>

<?php $this->endblock('main') ?>
