<!DOCTYPE html>
<html lang="en">
<head>
    <title>Knit By Smith | <?php echo $item->name ?></title>
    <script src="/js/jquery-1.4.2.min.js"></script>
    <script src="/js/jquery-ui-1.8.4.custom.min.js"></script>
    <link type="text/css" rel="stylesheet" media="all" href="/css/style.css" />
    <link href='http://fonts.googleapis.com/css?family=Arvo:regular,italic,bold,bolditalic' rel='stylesheet' type='text/css'>
    <?php $this->block( 'head' ); ?>
    <?php $this->endBlock( 'head' ); ?>
</head>
<body>
    <div id="page">
        <div id="navigation">
        <?php $this->block('navigation'); ?>
            <div id="nav-collection">
                <a class="<?php echo $request->primary == 'collection' ? 'active':''?>" href="/collection/">Collection</a>
                <?php if( $request->primary != 'home' ): ?>
                <span class="sep">|</span><a href="/">Home</a>
                <?php endif; ?>
            </div>
            <a class="<?php echo $request->primary == 'wat' ? 'active':''?>" href="/wat">Wat</a><span class="sep">|</span>
            <a class="<?php echo $request->primary == 'waar' ? 'active':''?>" href="/waar">Waar</a>
            <div id="logo">
                <a href="/">
                    <img alt="Knit By Smith | Home " src="/img/logo.png" />
                </a>
            </div>
        <?php $this->endBlock('navigation'); ?>
        </div>
        <div id="masthead">
        <?php $this->block('masthead') ?>
        <?php $this->endBlock('masthead') ?>
        </div>
        <div id="content">
        <?php $this->block('content'); ?>
        <?php $this->endBlock('content'); ?>
        </div>
    </div>
</body>
</html>
