<!DOCTYPE HTML>
<html lang="en">
<head>
    <title>Slicr::<?php echo $this->getRequest()->controller ?>::<?php echo $this->getRequest()->action; ?></title>
	<link type="text/css" rel="stylesheet" media="all" href="/css/style.css" />
    <script src="/js/prototype.js"></script>
    <script src="/js/scriptaculous/scriptaculous.js"></script>
</head>
<body>
    <div id="main">
		<div class="reps">
			<?php if( Nano_Session::session()->auth == true ): ?>
			<div id="header" class="wrap">
				<div class="wrap">
					<h1 class="float-left">PICO - site title</h1>
					<a href="/">view site</a> |
					<a href="/user/logout">logout</a>
				</div>
                <div id="main-menu">
                    <div class="wrap">
                        <?php echo $this->modules() ?>
                    </div>
                </div>
			</div>
            <?php endif; ?>
			<div id="main-content">
                <div id="main-left" class="reps">
                    <?php echo $this->mainLeft ?>
                </div>
                <?php if( $this->actions ): ?>
                <div id="menu-left" class="reps">
                    <h2 class="buttonbar">Actions</h2>
                        <div class="wrap">
                        <?php echo $this->linkList( $this->actions ) ?>
                        </div>
                </div>
                <?php endif; ?>
			</div>
		</div>
    </div>
</body>
</html>
