<?php $this->block('main') ?>
<div class="third">
    <form method="post" class="form image-bulk" action="/admin/image/bulk/<?php echo $label_id ?>">
        <table class="icon-select-list" cellpadding="0" cellspacing="0" border="0">
        <?php foreach( $images as $image ): ?>
            <tr>
                <td>
                    <input checked="yes" type="checkbox" id="image-<?php echo $image->id ?>" name="image[<?php echo $image->id ?>]" />                                    
                </td>
                <td>
                    <label for="image-<?php echo $image->id ?>">
                        <strong><?php echo $image->name ?></strong><br/>
                        <?php echo $image->description ?>
                    </label>                                    
                </td>
                <td>
                    <label class="icon" for="image-<?php echo $image->id ?>">
                        <img alt="<?php echo $image->name ?>" src="/image/icon/<?php echo $image->id ?>" />
                    </label>                                    
                </td>
            </tr>
        <?php endforeach; ?>            
        </table>
        <div class="toolbar">
            
            <input type="submit" class="input-submit" name="action-delete-confirm" value="Delete">
            <input type="submit" class="input-submit" name="cancel" value="Cancel">
        </div>
    </form>
<?php $this->endblock('main') ?>
