<!DOCTYPE html>
<html>
    <head>
        <title>weddingparty + hochzeitsfest + bruloft | Matthijs & Silke 24.06.2011</title>
        <meta charset="utf-8">
        <script type="text/javascript" src="http://use.typekit.com/pfe4iqu.js"></script>
        <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
        <link rel="stylesheet" type="text/css" href="css/style.css" media="screen" />
    </head>
    <body>
        <div id="content-wrap">
            <div id="header">
                <a id="button-rsvp" href="/construction.html"><img alt="rsvp" src="img/button-rsvp.png" /></a>                
            </div>
            <div id="page-body" class="home">
                <ul id="home-buttons">
                    <li><a href="/construction.html" id="directions" class="home-button">
                        <img src="/img/home-button-directions.png" alt="Directions, Anfahrt, route" />
                    </a></li>
                    <li><a href="/construction.html" id="schedule" class="home-button">
                        <img src="/img/home-button-schedule.png" alt="Schedule, Tagesablauf, planning" />
                    </a></li>
                    <li><a href="/construction.html" id="accomodation" class="home-button">
                        <img src="/img/home-button-accomodation.png" alt="Accomodation, Unterkunft, accomodatie" />
                    </a>
                    <li><a href="/construction.html" id="presents" class="home-button">
                        <img src="/img/home-button-presents.png" alt="Presents, Geschenke, kados" />
                    </a></li>
                </ul>
                <div id="content-item-1" class="content-item">
                    <h4>Dear Weddingguest,</h4>
                    <p>We are getting married on june 24th, 2011. Join us in our celebration!
                    On this website you can find all the information around that day: time
                    and place of the ceremony and party, directions, some tips according
                    accomadation and a wishlist plus a donation formular.</p>
                    <p>Let us know if you’ll be there!</p>
                </div>
                <div class="content-item" id="content-item-2">
                    <h4>Liebe Hochzeitsgäste,</h4>
                    <p>Am 24. Juni 2011 wird geheiratet und das muss gefeiert werden!
                    Auf dieser Webseite findet Ihr Informationen über Zeit und Ort von
                    Standesamt und Fest, Anfahrts Beschreibungen, Tips für Unterkünfte und
                    eine Liste met Geschenkwünschen und die Möglichkeit um hierfür zu
                    spenden.</p>
                    <p>Lasst uns wissen , ob Ihr kommt!</p>
                </div>
                <div class="content-item" id="content-item-3">
                    <h4>Lieve Gast,</h4>
                    <p>Op 24 Juni 2011 gaan wij trouwen, en dat moet worden gevierd!
                    Op deze website vind je informatie over de tijd en plaats van ons trouwen en
                    het feest, routebeschrijvingen, tips voor accomodatie en een lijstje
                    met onze dromen en verlangens en de mogelijkheid om hiervoor te
                    ‘doneeren’.</p><p>Laat ons even weten of je komt!</p>
                </div>
            </div>
            <div id="footer">
            </div>
        </div>
    </body>
</html>