<?php $this->inherit( dirname(__file__) . '/layout') ?>

<?php $this->block('content'); ?>
<div id="page-header" class="<?php echo $item->slug ?>">
    <h1 class="<?php echo $item->slug ?>"><?php echo $item->name ?></h1>
    <menu class="page-nav">
        <li><a href="/">home</a></li>        
        <?php foreach( array('directions', 'schedule', 'gifts', 'accomodation') as $slug ): ?>
        <li><a href="/<?php echo $slug ?>" class="<?php echo $slug == $item->slug ? 'active' : ''; ?>"><?php echo $slug ?></a></li>        
        <?php endforeach; ?>
    </menu>
    <div class="subtitle">
        <?php echo $item->description ?>
    </div>
</div>
<div id="body-wrap">
<div id="body-<?php echo $item->slug ?>" class="content">
<?php foreach( $item->content as $key => $content ): ?>
    <?php echo $key > 2 ? '</div><div class="additional">' : '' ?>
    <div id="content-item-<?php echo $key ?>" class="content-item">
        <?php echo $content; ?>
    </div>
<?php endforeach; ?>
</div>
</div>

<?php $this->endBlock('content') ?>