<?php $this->inherit( dirname(__file__) . '/layout') ?>

<?php $this->block('content'); ?>
<div id="page-header" class="<?php echo $item->slug ?>">
    <h1 class="<?php echo $item->slug ?>"><?php echo $item->name ?></h1>
    <menu class="page-nav">
        <li><a href="/">home</a></li>        
        <?php foreach( array('directions', 'schedule', 'gifts', 'accomodation') as $slug ): ?>
        <li><a href="/<?php echo $slug ?>" class="<?php echo $slug == $item->slug ? 'active' : ''; ?>"><?php echo $slug ?></a></li>        
        <?php endforeach; ?>
    </menu>
    <div id="subtitle">
        <?php echo $item->description ?>
    </div>
</div>
<div id="tablewrap-<?php echo $item->slug ?>">
<table>
    <tr>
        <th>
<strong>Stadsdeelhuis Oost</strong><br/>
Oranje-Vrijstaatplein 2<br/>
1093 NG Amsterdam       
        </th>
        <th>
<strong>Restaurant De Kas</strong><br/>
Kamerlingh Onneslaan 3<br/>
1097 DE Amsterdam
        </th>
        <th>
<strong>KHL</strong><br/>
Oostelijke Handelskade 44<br/>
1019 BN Amsterdam
        </th>
    </tr>
    <tr>
        <td>
<big>11.00</big>
<big class="en">Ceremony</big>
<big class="de">Trauung</big>
<big class="nl">Trouwceremonie</big>
<small>* Everyone who wants to come is
welcome, but there might not be
enough room for everbody.</small>
        </td>
        <td>
<big>12.30</big>
<big>Lunch with our family</big>
<big class="de">Mittagessen mit Familie</big>
<big class="nl">Eten met familie</big>
        </td>
        <td>
<big>18.00</big>
<big>Party</big>
        </td>
    </tr>
</table>


</div>
<div id="body-<?php echo $item->slug ?>" class="content">
<?php foreach( $item->content as $key => $content ): ?>
    <div id="content-item-<?php echo $key ?>" class="content-item">
        <?php echo $content; ?>
    </div>
<?php endforeach; ?>
</div>

<?php $this->endBlock('content') ?>