<?php $this->wrapper( 'layout')  ?>

<?php $this->block('content'); ?>
<?php $this->process( 'blocks/pager'); ?>
<div class="imagelist">
    <ul class="imagelist">
    <?php foreach( $images as $image ): ?>
        <li class="<?php echo $this->cycle('left', 'center', 'right') ?>">
            <a style="background-image: url('/image/vignette/<?php echo $image->id ?>')" href="/<?php echo $image->slug ?>">
                <img src="/image/vignette/<?php echo $image->id ?>" alt="" />
            </a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php $this->process( 'blocks/pager'); ?>
<?php $this->endBlock('content'); ?>
