<!DOCTYPE html>
<html lang="en">
<head>
    <title>This is an example | <?php echo $item ? $item->name : 'home' ?></title>
    <link type="text/css" rel="stylesheet" media="all" href="/public/css/style.css" />
    <?php $this->block( 'head' ); ?>
    <?php $this->endBlock( 'head' ); ?>
</head>
<body>
    <div id="page">
        <div id="navigation">
        <?php $this->block('navigation'); ?>
        <?php $this->endBlock('navigation'); ?>
        </div>
        <div id="masthead">
        <?php $this->block('masthead') ?>
        <?php $this->endBlock('masthead') ?>
        </div>
        <div id="content">
        <?php $this->block('content'); ?>
        <?php $this->endBlock('content'); ?>
        </div>
    </div>
</body>
</html>
