<!DOCTYPE html>
<html lang="en">
<head>
    <title>Pictures | <?php echo $item->name ?></title>
    <script src="/js/jquery-1.4.2.min.js"></script>
    <script src="/js/jquery-ui-1.8.4.custom.min.js"></script>
    <link type="text/css" rel="stylesheet" media="all" href="/public/style.css" />
    <?php $this->block( 'head' ); ?>
    <?php $this->endBlock( 'head' ); ?>
</head>
<body>
    <div id="page">
        <div id="navigation">
        <?php $this->block('navigation'); ?>
            <ul><?php foreach( $labels as $label ): ?>
                <li><a class="<?php $label->slug ?>" href="/<?php echo $label->slug ?>"><?php echo $label->name ?></a></li>
            <?php endforeach; ?>
            </ul>
        <?php $this->endBlock('navigation'); ?>
        </div>
        <div id="masthead">
        <?php $this->block('masthead') ?>
        <?php $this->endBlock('masthead') ?>
        </div>
        <div id="content">
        <?php $this->block('content'); ?>
        <?php $this->endBlock('content'); ?>
        </div>
    </div>
</body>
</html>
