<?php $this->wrapper('layout') ?>

<?php $this->block( 'head' ); ?>
<?php $this->endBlock('head'); ?>

<?php $this->block('titlebar') ?>
<h2 class="title">video</h2>
<a href="/admin/video/create" class="context-button">new page</a>
<?php $this->endblock('titlebar') ?>


<?php $this->block('main') ?>
<ul class="itemlist">
    <li>
        <strong class="fifth">Title</strong>
        <strong class="half">Description</strong>
    </li>
    <?php foreach( $this->items('video', array(), false ) as $page ): ?>
    <li>
        <div class="fifth">
            <h6><?php echo $page->name ?></h6>
            <div class="buttons">
                <a href="/admin/video/edit/<?php echo $page->id ?>" class="button third">edit</a>
                <a href="/admin/video/delete/<?php echo $page->id ?>" class="button third">delete</a>
            </div>
        </div>
        <p class="half"><?php echo $this->ellipsize((string)$page->description) ?>&nbsp;</p>
        <p class="fifth"><strong>updated:</strong><br/><?php echo $page->updated ?></p>
    </li>
    <?php endforeach; ?>
</ul>
<?php $this->endblock('main') ?>