<style>
#builder-box {
    background: #fff;
    height: 100%;
    margin: 0.5em;
    min-height: 840px;
    overflow: auto;
}


.element-block{
    border: 1px solid red;
    background-color: #444;
    position: relative;
    margin: 20px;
}

.margin {
    position: absolute;
    background-color: #f9f9f9;
    top: 0px;
    left: 0px;
    right: 0px;
    bottom: 0px;
    border: 1px solid #f6f6f6;
    border-bottom: 1px solid #e9e9e9;
    border-right: 1px solid #e9e9e9;

}

.inner {
    position: relative;
    background-color: #eee;
    border: 1px solid #f3f3f3;
    border-bottom: 1px solid #e3e3e3;
    border-right: 1px solid #e3e3e3;
}

.handle{
    height: 1.5em;
    background-color: #999;
    font: bold 12px sans-serif;
    color: #fff;
    padding: 0 0.2em;
}

.width-spacer{
    min-width: 4em;
}

.height-spacer{
    min-height: 2em;
    overflow: auto;
    position: relative;
}

input {
    border: 1px solid red;
}
/*
.padder{
    position: absolute;
    top: 0px;
    left: 0px;
    right: 0px;
    bottom: 0px;
}

.body {
    position: relative;
    background-color: #F9F9F9;
    width: 100%;
    height: 100%;


}
*/

</style>
